using System;
using System.Collections.Generic;
using System.Text;

namespace CJ_Controls.Communication.YaskawaLoader
{
	public enum SEQ_INITIAL_STATUS
	{
		INITIAL_START,		// Initialize
		INITIAL_RESTART,	// Initialize
		READY,		// Processing
		NONE,
	}

	public enum ORIGIN_UNIT_NO : int
	{
		ALL_THE_EQUIPMENT = 0,
		ROBOT = 1,
		MAPPING_UNIT = 2,
		CASSETTE_PORT = 3,
	}
	public enum RETURN_ORIGIN_UNIT_STATUS
	{
		FINISH,
		ROBOT_ON_MOVE,
		ERROR,
		ACCEPTANCE_REJECTED,
		NOT_REMOTE_MODE,
		PARAMETER_ERROR,

		NONE,
	}
	public enum CONTROLLER_STATUS
	{
		REMOTE = 0,
		LOCAL,
		NONE,
	}
	public enum TEMPORARY_STOPPING : int
	{
		ON_RUN = 0,
		PAUSE,
	}
	public enum CASSETTE_STATUS : int
	{
		NO_CASSETTE = 0,
		HAVE_CASSETTE,
		ERROR_STATUS,
		NOT_DEFINED,
	}

	public enum CASSETTE_PRESENT_STATUS : int
	{
		NORMAL = 0, // Normal
		NOT_IN_REMOTE, // Not in remote

		NONE,
	}
	public enum PORT_STATUS : int
	{
		EMPTY = 0,	//초기상태 및 Casstte Move Out 이후
		IDLE,		//Cassette Move In 이후
		WAITING,	//Mapping Finished 이후
		RESERVE,	//Start Standby (R60) 이후
		BUSY,		//Lot Start (R61) 이후
		COMPLETE,	//Lot Finished Clamp Open 이후
		DISABLE = 8,
		ERROR = 9,
	}
	public enum OPERATION_TYPE : int
	{
		REQUEST_GET_STANDBY = 1,
		REQUEST_Y_ALIGMENT = 2,
		REQUEST_GET_THE_SUBSTRATE = 3,
		REQUEST_PUT_STANDBY = 4,
		REQUEST_PUT_THE_SUBSTRATE = 5,
		REQUEST_GET_THE_SUBSTRATE_DOUBLE_ARM = 6,
		REQUEST_PUT_THE_SUBSTRATE_DOUBLE_ARM = 7,
		PLATE_ID_READ_STANDBY = 8,
		REQUEST_EXCHANGE = 9,
		NONE = 10,
	}
	public enum INITIALIZE_STATUS
	{
		SUCCESS,
		ERROR,
		NOT_REMOTE_MODE,
		ROBOT_ON_MOVE,
		REFUSE_MESSAGE,
	}
	public enum PORT_MODE : int
	{
		AGV = 0,
		MGV,
		DISABLE,
	}
	public enum ALARM_STATUS_RESULT : int
	{
		HAVE_NO_GLASS = 0,
		HAVE_GLASS,
		NO_REMOTE_MODE,
		NONE,
	}
	public enum ALARM_STATUS
	{
		NO_ALARM,
		ALARM_STATUS,
	}

	public enum AGV_MODE_CHANGE_RESULT
	{
		RECEIVE_ON_NORMAL,
		BUSY,
		REFUSE_MESSAGE,
		PARAMETER_ERROR,
	}

	public enum CASSETTE_ENABLE_MODE
	{
		RECEIVE_ON_NORMAL,
		NOT_REMOTE_MODE,
		BUSY,
		APPOINTED_PORT_HAS_NOT_BEEN_REGISTERED,
		PARAMETER_ERROR,
	}

	public enum PORT_STARTPREPARATION_RESULT
	{
		REQUEST_IS_ON_ACCEPTING,
		ON_ERROR,
		ON_WORKING,
		NOT_REMOTE_MODE,
		HAVE_NOT_RETURN_TO_ORIGIN,
		THE_PORT_OF_APPOINT_HAS_NOT_CASSETTE,
		ACCEPTANCE_REFUSAL,
		THE_PORT_OF_APPOINT_HAS_NOT_BEEN_REGISTERED,
		THE_PORT_OF_APPOINT_IS_ON_DISABLE,
		PARAMETER_ERROR,
		NONE,
	}

	public enum INFORM_THE_SUBSTRATE_TRANSFER : int
	{
		REQUEST_ACCEPTED,
		ERROR_HAPPENED,
		BUSY,
		REMOTE_MODE_NOT_AVAILABLE,
		RETURN_TO_ORIGINAL_WAS_NOT_EXECUTED,
		NO_SUBSTRATE_EXISTING_AT_THE_LOADING_POSITION,
		SUBSTRATE_EXISTING_AT_THE_LOADING_POSITION,
		PAUSING,
		THE_INDICATED_STAGE_IS_NOT_REGISTERED,
		MESSAGE_REJECTED,
		PARAMETER_ERROR,
	}

	public enum SUBSTRATE_TRANSPORT_RESULTS : int
	{
		NORMAL_FINISHED,
		ABNORMAL_FINISHED,
		SUBSTRATE_CHUCKING_ERROR,
		NONE,
	}

	public enum ROBOT_PAUSE_RESUME_RESULTS : int
	{
		FINISHED_NORMALLY,
		NOT_PAUSE_CONDITION,
		ERROR_OCCURRED,
		NOT_REMOTE_MODE,
		IN_FORCED_STOPPING,
	}

	public enum PORT_CARRYING_IN_OUT : int
	{
		MOVE_IN_CASSETTE = 0,
		MOVE_OUT_CASSETTE,
		NONE,
	}

	public enum PORT_CARRYING_IN_OUT_RESULT : int
	{
		FINISHED = 0,
		BCR_MALFUNCTION,
		NONE,
	}

	public enum PORT_UNCLAMP_RESULT : int
	{
		ACTION_FINISHED = 0,
		ERROR_HAPPENED,
		NOT_UNDER_REMOTE_MODE,
		REJECTED,
		PARAMETER_ERROR,
	}

	public enum REPLY_PORT_RECHUCK
	{
		REQUEST_ACCEPTED,
		ERROR_HAPPENED,
		MOVING,
		REMOTE_MODE_NOT_AVAILABLE,
		RETURN_TO_ORIGINAL_NOT_BEEN_EXECUTED,
		THERE_IS_NO_CASSETTE_ON_THE_INDICATE_PORT,
		THE_INDICATED_PORT_IS_NOT_REGISTER,
		THE_COMMAND_WAS_REJECTED,
		PARAMETER_ERROR,
	}

	public enum REQUEST_MAPPING_PORT_RESULTS : int
	{
		REQUEST_ACCEPTED,
		MOVING,
		NOT_REMOTE_MODE,
		REQUEST_BEEN_REJECTED,
		PARAMETER_ERROR,
	}

	public enum MAPPING_PORT_RESULTS : int
	{
		MAPPING_FINISHED_NORMALY,
		ERROR_HAPPNED,

		NONE,
	}

	public enum ALARM_HAPPENED_LEVEL : int
	{
		ALL_THE_ERROR_BEEN_CANCELLED = 0,
		ERROR_CAN_RETRY,
		ERROR_CAN_NOT_RETRY,
		DIRECT_TO_OFF_THE_BUZZER_IGNORE_ALL_THE_OTHER,
		WARNING_OPERATION_IS_CONTINUTING,
		NONE,
	}

	public enum ALARM_HAPPENED_EQP_DIVISION : int
	{
		CONTROLLER = 0,
		CASSETTE_ID,
		ROBOT,
		MAPPING_UNIT,
		PORT,
		TURN_TABLE,
	}

	public enum ALARM_RESET_RESULTS : int
	{
		REQUEST_ACCEPTED,
		NOT_REMOTE_MODE,
		ALARM_IS_NOT_LEVEL_1,
		PARAMETER_ERROR,
	}

	public enum STAGE : int
	{
		NONE = 0,
		PORT_1,
		PORT_2,
		PORT_3,
		PORT_4,
		PORT_5,
		PORT_6,
		EQP_1,
		EQP_2,
		EQP_3,
		EQP_4,	//SPECIAL_A,
		EQP_5,	//SPECIAL_B,
		EQP_6,	//SPECIAL_C,
		ID_READ_POS1,
		ID_READ_POS2,
	}

	public enum ROBOT_HAND : int
	{
		HAND_UPPER = 1,
		HAND_LOWER = 2,
	}

	public enum THICKNESS : int
	{
		//Ver.2.02 : 로더 엔지니어가 우리한테 말해주기로함. 나중에 2.06으로 변경.
		THICKNESS_0_3 = 2,
		THICKNESS_0_4 = 3,
		THICKNESS_0_5 = 1,
		THICKNESS_0_7 = 4,

		//Ver.2.06
		//THICKNESS_0_3 = 1,
		//THICKNESS_0_4 = 2,
		//THICKNESS_0_5 = 3,
		//THICKNESS_0_7 = 4,
	}
}
